#
# cmake/reflect/_Headers.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/reflect
)

set( PRIVATE_GENERATED_HEADERS
src/reflect/_mulle-thread-include-private.h
)

set( PRIVATE_HEADERS
src/include-private.h
)

set( PUBLIC_GENERATED_HEADERS
src/reflect/_mulle-thread-include.h
)

set( PUBLIC_HEADERS
src/include.h
src/mulle-atomic-c11.h
src/mulle-atomic.h
src/mulle-atomic-mintomic.h
src/mulle-thread-c11.h
src/mulle-thread.h
src/mulle-thread-pthreads.h
src/mulle-thread-windows.h
)

