/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_C_HEADERS_FILE DISABLE
 *
 *   To not let mulle-match-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_RUN DISABLE
 */
#ifndef _mulle__thread__provide_h__
#define _mulle__thread__provide_h__


#include "mulle-atomic-c11.h"
#include "mulle-atomic.h"
#include "mulle-atomic-mintomic.h"
#include "mulle-thread-c11.h"
#include "mulle-thread-pthreads.h"
#include "mulle-thread-windows.h"


#endif
