/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_thread_include_private_h__
#define _mulle_thread_include_private_h__

/* no headers */

#endif
