/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_thread_include_h__
#define _mulle_thread_include_h__

# include <mulle-c11/mulle-c11.h>   // mulle-c11

# include <pthread.h>   // pthread

#endif
