# cmake/_Dependencies.cmake is generated by `mulle-sde`. Edits will be lost.
# Last update: 2018-03-14 00:09:13
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

if( NOT MULLE_C11_HEADER)
   find_file( MULLE_C11_HEADER NAMES mulle-c11)
   message( STATUS "MULLE_C11_HEADER is ${MULLE_C11_HEADER}")
   set( HEADER_ONLY_LIBRARIES
      ${MULLE_C11_HEADER}
      ${HEADER_ONLY_LIBRARIES}
      CACHE INTERNAL "need to cache this"
   )
   if( MULLE_C11_HEADER)
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( TMP_MULLE_C11_ROOT "${MULLE_C11_HEADER}" DIRECTORY)
      set( MEMO_CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH}")
      list( INSERT CMAKE_MODULE_PATH 0 "${TMP_MULLE_C11_ROOT}/cmake")
      # use explicit path to avoid "surprises"
      unset( ${MULLE_C11_DEFINITIONS)
      include( "${TMP_MULLE_C11_ROOT}/cmake/DependenciesAndLibraries.cmake" OPTIONAL)
      set( CMAKE_MODULE_PATH "${MEMO_CMAKE_MODULE_PATH}")

      set( INHERITED_DEFINITIONS
           ${MULLE_C11_DEFINITIONS}
           ${INHERITED_DEFINITIONS}
      )
  endif()
endif()
