# cmake/_Dependencies.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

if( NOT MULLE_C11_HEADER)
   find_file( MULLE_C11_HEADER NAMES mulle-c11.h mulle-c11/mulle-c11.h)
   message( STATUS "MULLE_C11_HEADER is ${MULLE_C11_HEADER}")
   set( ALL_LOAD_HEADER_ONLY_LIBRARIES
      ${MULLE_C11_HEADER}
      ${ALL_LOAD_HEADER_ONLY_LIBRARIES}
      CACHE INTERNAL "need to cache this"
   )
   if( MULLE_C11_HEADER)
      # search for DependenciesAndLibraries.cmake to include
      get_filename_component( _TMP_MULLE_C11_DIR "${MULLE_C11_HEADER}" DIRECTORY)
      set( _TMP_MULLE_C11_DIR "${_TMP_MULLE_C11_DIR}/cmake")
      # use explicit path to avoid "surprises"
      if( EXISTS "${_TMP_MULLE_C11_DIR}/DependenciesAndLibraries.cmake")
         unset( MULLE_C11_DEFINITIONS)
         list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_C11_DIR}")
         include( "${_TMP_MULLE_C11_DIR}/DependenciesAndLibraries.cmake")
         list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_C11_DIR}")
         set( INHERITED_DEFINITIONS
               ${INHERITED_DEFINITIONS}
               ${MULLE_C11_DEFINITIONS}
               CACHE INTERNAL "need to cache this"
         )
      endif()
   else()
      message( FATAL_ERROR "MULLE_C11_HEADER was not found")
   endif()
endif()
