# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
# Last update: 2018-03-14 00:09:12
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
) 

set( HEADERS
src/dependencies.h
src/mulle_atomic_c11.h
src/mulle_atomic.h
src/mulle_atomic_mintomic.h
src/mulle_thread_c11.h
src/mulle_thread.h
src/mulle_thread_pthreads.h
src/mulle_thread_windows.h
) 

