# cmake/_Libraries.cmake is generated by `mulle-sde`. Edits will be lost.
# Last update: 2018-03-14 00:09:13
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

# there are no libraries in the sourcetree
